list =[]
inp1 = input("Enter 1st number")
inp2 = input("Enter 2nd number")
inp3 = input("Enter 3rd number")
inp4 = input("Enter 4th number")
inp5 = input("Enter 5th number")
inp6 = input("Enter 6th number")
inp7 = input("Enter 7th number")
inp8 = input("Enter 8th number")
inp9 = input("Enter 9th number")
inp10 = input("Enter 10th number")
last = input("\n\nEnter the number that you want to check")
list.append(inp1)
list.append(inp2)
list.append(inp3)
list.append(inp4)
list.append(inp5)
list.append(inp6)
list.append(inp7)
list.append(inp8)
list.append(inp9)
list.append(inp10)
if last in list :
    print ("yes,",last," is in the list")
else:
    print ("no,",last," is not in the list")
